lista = ["ordenador", "mesa", "monitor",["raton", "alfombirlla", "teclado"]]
print(lista)
print("-----------------------------------------------------------------------")
print(lista[0])
print(lista[1])
print(lista[2])
print(lista[3])
print(lista[3][0])
print(lista[3][1])
print(lista[3][2])